# Generated by Django 6.0.6 on 2026-06-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('category', models.CharField(choices=[('挂号费', '挂号费'), ('诊疗费', '诊疗费'), ('检查费', '检查费'), ('药费', '药费')], max_length=20, verbose_name='类别')),
            ],
            options={
                'verbose_name': '收费项目',
                'verbose_name_plural': '收费项目',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科室名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科室',
                'verbose_name_plural': '科室',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('allergy_history', models.TextField(blank=True, verbose_name='过敏史')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(choices=[('主治医师', '主治医师'), ('副主任医师', '副主任医师'), ('主任医师', '主任医师')], max_length=20, verbose_name='职称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像URL')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('status', models.SmallIntegerField(choices=[(1, '在职'), (0, '离职')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.department', verbose_name='所属科室')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生',
                'ordering': ['-status', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('appointment_time', models.TimeField(verbose_name='预约时间')),
                ('status', models.SmallIntegerField(choices=[(0, '待确认'), (1, '已确认'), (2, '就诊中'), (3, '已完成'), (4, '已取消'), (5, '爽约')], default=0, verbose_name='状态')),
                ('symptom', models.TextField(blank=True, verbose_name='症状描述')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor', verbose_name='医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='诊断结果')),
                ('prescription', models.TextField(blank=True, verbose_name='处方/用药建议')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='就诊时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment', verbose_name='关联预约')),
            ],
            options={
                'verbose_name': '病历',
                'verbose_name_plural': '病历',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实收金额')),
                ('status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '已支付')], default=0, verbose_name='支付状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment', verbose_name='关联预约')),
                ('charge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.chargeitem', verbose_name='收费项目')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.SmallIntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='上班时间')),
                ('end_time', models.TimeField(verbose_name='下班时间')),
                ('max_patients', models.IntegerField(default=20, verbose_name='最大接诊人数')),
                ('is_off', models.BooleanField(default=False, verbose_name='是否休息')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor', verbose_name='医生')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'unique_together': {('doctor', 'week_day')},
            },
        ),
    ]
